# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], max_length=1)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('quantity', models.FloatField(default=0.0)),
                ('quantity_units', models.CharField(choices=[('K', 'KG'), ('P', 'Pack'), ('L', 'Litter'), ('M', 'Meter')], max_length=1)),
                ('expected_price', models.FloatField(default=0.0)),
                ('actual_price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Done'), ('R', 'Reject')], max_length=1)),
                ('check_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_list.CheckList')),
            ],
        ),
    ]
