# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('quantity', models.FloatField(default=0.0)),
                ('quantity_units', models.CharField(choices=[('K', 'KG'), ('P', 'Pack'), ('L', 'Liter'), ('M', 'Meter')], max_length=1)),
                ('expected_price', models.FloatField(default=0.0)),
                ('actual_price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Done'), ('R', 'Reject')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='listitem',
            name='quantity_units',
            field=models.CharField(choices=[('K', 'KG'), ('P', 'Pack'), ('L', 'Liter'), ('M', 'Meter')], max_length=1),
        ),
    ]
