# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0002_auto_20160418_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
