# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0003_auto_20160418_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='expected_price',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='quantity_units',
        ),
    ]
