# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0004_auto_20160418_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemToItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_list.ListItem')),
                ('item_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_list.ListItemDescription')),
            ],
        ),
    ]
