# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0005_itemtoitemdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtoitemdescription',
            old_name='custom_item',
            new_name='custom_item_id',
        ),
        migrations.RenameField(
            model_name='itemtoitemdescription',
            old_name='item_description',
            new_name='item_description_id',
        ),
    ]
